services:
  mongodb:
    image: mongo
    container_name: mongo_db
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    networks:
      - mern-network

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - 8080:8080
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
      - ME_CONFIG_MONGODB_SERVER=mongodb
    networks:
      - mern-network

  app-blog:
    build:
      context: ./app-blog  # Path to the backend code
    container_name: app-blog
    ports:
      - "9000:9000"
    networks:
      - mern-network
    environment:
      - MONGO_URI=mongodb://root:root@mongodb:27017
  
  client:
    build:
      context: ./client  # Path to the frontend code
    container_name: client
    ports:
      - "3000:3000"
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge

volumes:
  mongo: {}
